version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/cxmate/cxmate
    steps:
      - checkout
      - run: go test $(go list ./... | grep -v /vendor/)
